### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by mello7tre** [mello7tre/AwsIBox#1]
Need to add documentation and working instructions in README

**Comment by as485** [comment]
Hi there, I was reading the code of the function "do_no_override" in AwslBox\awsibox\shared.py. My understanding is "check for the currently logged-in user has its associated form". Did I understand that right?”

**Comment by as485** [comment]
Hi there, I was reading the code of the function "import_modules" in AwslBox\awsibox\shared.py. My understanding is "try to ensure the modules were modules". Did I understand that right?”

**Comment by as485** [comment]
Hi there, I was reading the code of the function "import_lambda" in AwslBox\awsibox\shared.py. My understanding is "returns true if Harvard annotation tool is enabled for the course". Did I understand that right?”

**Comment by as485** [comment]
Hi there, I was reading the code of the function "auto_build_obj" in AwslBox\awsibox\shared.py. My understanding is "filter_template string containing %s as placeholder for assertion variable". Did I understand that right?”
